### ISSUE TITLE
When multiple links are included in a Slack message, only one link appears on IRC (the message is cut)

### ISSUE THREAD

**Issue by japsu** [ekmartin/slack-irc#160]
Using latest HEAD from today. Been riddled with this problem for a long time, though.

Steps to reproduce: Say `tracon.fi desucon.fi` on a connected channel in Slack

Expected results: `<yournick> tracon.fi desucon.fi` is reproduced in IRC

Actual results: `<yournick> desucon.fi` in IRC

Also happens with e-mail addresses.

**Comment by ekmartin** [comment]
Woops! Thanks. Should be fixed in version 3.8.3.

**Comment by japsu** [comment]
Thanks @ekmartin for the super-fast reply.

Unfortunately, running version 3.8.3, I'm still experiencing the same problem.

This works: `https://desucon.fi https://tracon.fi`
This doesn't: `desucon.fi tracon.fi`

If it makes any difference, I'm trying this on a private channel (no #).

Environment:

Running this docker image https://hub.docker.com/r/tracon/slackirc/
built from this Dockerfile https://github.com/tracon/ansible-tracon/blob/master/roles/slackirc/Dockerfile

**Comment by ekmartin** [comment]
Sorry, had to make the readable representation regex non-greedy as well: https://github.com/ekmartin/slack-irc/commit/1ffd30fd3cf4a61a0fbc052ff5d600bf63f4da0e

Please give version 3.8.4 a go and see if it fixes it. Thanks for the thorough report!

**Comment by japsu** [comment]
Thanks, working now!

**Comment by japsu** [comment]
@ekmartin I assume this is related:

Say in Slack: `java.util.List<java.lang.String>`

Appears in IRC: `java.util.Listjava.lang.String`

**Comment by ekmartin** [comment]
😞 - I'll take a look at it later :)

**Comment by japsu** [comment]
@jlaunonen just submitted a PR that probably fixes that :)

https://github.com/ekmartin/slack-irc/pull/161
