### ISSUE TITLE
NPM start fails

### ISSUE THREAD

**Issue by c0ding** [ekmartin/slack-irc#29]
Hi there,

I was playing around with your code, trying to add server password and server port support but then I ran into this issue:

```
npm ERR! slack-irc@3.3.0 start: `node index.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the slack-irc@3.3.0 start script.
npm ERR! This is most likely a problem with the slack-irc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls slack-irc
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-0.bpo.4-amd64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /root/slack-irc
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/slack-irc/npm-debug.log
npm ERR! not ok code 0
```
This happens even after a clean clone from your repo.

Cheers.

**Comment by ekmartin** [comment]
If you scroll a bit further up in the error log you should see the following error: `Error: Missing environment variable CONFIG_FILE`. This means that you need to export the environment variable `CONFIG_FILE` so slack-irc knows which config you're referring to, i.e. `export CONFIG_FILE="./config.json`. 

This is the same as running `node index.js --config ./config.json`, but to send command line arguments to `npm start` you need to do `npm start -- --config ./config.json` (notice the extra `--`).

Also, in regards to your fork, you can pass options directly to node-irc by using `ircOptions`. Example:
```js
"ircOptions": {
  "port": 1337,
  "password": "some password"    
}
```

**Comment by ekmartin** [comment]
@c0ding I updated the README to make it clearer now (https://github.com/ekmartin/slack-irc/commit/f1be24ed6761bf29348d32cc1a48323281132d3a) - did you get it to work?

**Comment by c0ding** [comment]
@ekmartin that fixed the issue, thanks. :+1: 
Still not working because the bot is not connecting to the IRC server, but that might be a server issue.

**Comment by ekmartin** [comment]
Might be, is it a public IRC server?

**Comment by c0ding** [comment]
Nope, private server. I've found a temporary workaround in adding ```"selfSigned" : true``` to the config file, even if the cert. comes from StartSSL.
Probably not using the chained cert., hence the issue.

Thank you for your help anyway, awesome work you did there. Definitely earned your Github :star: from me :smile: .

Cheers.

**Comment by ekmartin** [comment]
Hm, weird. Thanks for the feedback :smile:
